name: Release

on: { push: { tags: '**@[0-9]+.[0-9]+.[0-9]+*' } }

jobs:
  release:
    name: Release & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # for creating a GitHub release
      id-token: write # for publishing to npm with provenance
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with: { ref: 'main' } # attach HEAD to 'main'

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with: { version: latest }

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with: { node-version: latest, cache: pnpm, registry-url: https://registry.npmjs.org }

      - name: Set env variables
        run: |
          [[ $TAG =~ ^((@.+?\/)?(.+))@(.+)$ ]]
          PACKAGE=${BASH_REMATCH[1]}
          DIR=${BASH_REMATCH[3]}
          VERSION=${BASH_REMATCH[4]}
          ARCHIVE=${PACKAGE/@rawstyle\//rawstyle-}-v$VERSION.zip
          echo -e "DIR=$DIR\nPACKAGE=$PACKAGE\nVERSION=$VERSION\nARCHIVE=$ARCHIVE" >> $GITHUB_ENV

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm build:prod

      - name: Test
        run: pnpm test

      - name: Lint
        working-directory: packages/${{ env.DIR }}
        run: pnpm lint

      - name: Create release archive
        working-directory: packages/${{ env.DIR }}
        run: |
          cp ../../LICENSE .
          zip -r $ARCHIVE dist package.json LICENSE \
            $([[ $DIR == "rawstyle" ]] && cp ../../README.md . && echo README.md || true)
          rm -f LICENSE README.md

      - name: Publish to npm
        working-directory: packages/${{ env.DIR }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public --provenance

      - name: Create GitHub release
        working-directory: packages/${{ env.DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $TAG --title $TAG --draft $ARCHIVE