name: Release

on: { push: { tags: '*@[0-9]+.[0-9]+.[0-9]+*' } }

jobs:
  release:
    name: Release & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # for creating a GitHub release
      id-token: write # for publishing to npm with provenance
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with: { ref: 'main' } # attach HEAD to 'main'

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with: { version: latest }

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with: { node-version: latest, cache: pnpm, registry-url: https://registry.npmjs.org }

      - name: Set env variables
        run: |
          [[ $TAG =~ ([^/@]+)@ ]] && echo PACKAGE=${BASH_REMATCH[1]} >> $GITHUB_ENV
          echo VERSION=${TAG#*@} >> $GITHUB_ENV
          echo ARCHIVE=${PACKAGE/@rawstyle\//rawstyle}-v$VERSION >> $GITHUB_ENV

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm build:prod

      - name: Lint
        working-directory: packages/${{ env.PACKAGE }}
        run: pnpm lint

      - name: Create release archive
        working-directory: packages/${{ env.PACKAGE }}
        run: |
          cp ../../LICENSE .
          zip -r $ARCHIVE dist package.json LICENSE \
            $([[ $PACKAGE == "rawstyle" ]] && cp ../../README.md . && echo README.md)
          rm LICENSE README.md 2>/dev/null

      - name: Create GitHub release
        working-directory: packages/${{ env.PACKAGE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $TAG --title $TAG --draft $ARCHIVE

      - name: Publish to npm
        working-directory: packages/${{ env.PACKAGE }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public --provenance